name: Publish dev container images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    strategy:
      matrix:
        include:
          - language: python
            version: "3.8"
          - language: python
            version: "3.9"
          - language: python
            version: "3.10"
          - language: python
            version: "3.11"
          - language: python
            version: "3.12"
          - language: node
            version: "20"
          - language: node
            version: "18"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/orgs/community/discussions/10553#discussioncomment-7270402
      - name: Lowercase repository name
        id: lower
        shell: bash
        run: echo "image=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            VERSION=${{ matrix.version }}
          context: ${{ matrix.language }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ steps.lower.outputs.image }}/${{ matrix.language }}:${{ matrix.version }}
