name: Build Devcontainers

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    strategy:
      matrix:
        include:
          # - language: python
          #   version: "3.9"
          #   tag: "3.9"
          # - language: python
          #   version: "3.10"
          #   tag: "3.10"
          - language: python
            version: "3.11"
            tag: "3.11"
          - language: python
            version: "3.12"
            tag: "3.12"
          - language: python
            version: "3.13"
            tag: "3.13"
          - language: python
            version: "3.13"
            tag: latest
          - language: node
            version: "18"
            tag: "18"
          - language: node
            version: "20"
            tag: "20"
          - language: node
            version: "20"
            tag: "latest"

    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/orgs/community/discussions/10553#discussioncomment-7270402
      - name: Lowercase repository name
        id: lower
        shell: bash
        run: echo "image=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        id: dockerbuild
        with:
          cache-from: type=gha
          cache-to: type=gha
          context: . # build will fail without this
          build-args: |
            VERSION=${{ matrix.version }}
          file: ${{ matrix.language }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.lower.outputs.image }}/${{ matrix.language }}:${{ matrix.tag }}

      - name: Create Attestation
        id: attest
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ steps.lower.outputs.image }}/${{ matrix.language }}
          subject-digest: ${{ steps.dockerbuild.outputs.digest }}
          push-to-registry: false