name: Publish dev container images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - language: python
            version: "3.8"
          - language: python
            version: "3.9"
          - language: python
            version: "3.10"
          - language: python
            version: "3.11"
          - language: python
            version: "3.12"
          - language: node
            version: "20"
          - language: node
            version: "18"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            VERSION=${{ matrix.version }}
          context: ${{ matrix.language }}
          push: true
          tags: ${{ github.repository_owner_id}}/${{ matrix.language }}:${{ matrix.version }}
