name: Build Devcontainers

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    strategy:
      matrix:
        language: ["python", "node"]

    permissions:
      contents: read
      packages: write

    uses: NathanVaughn/reusable-actions/.github/workflows/docker-build-push.yml@main
    with:
      tags: ghcr.io/nathanvaughn/devcontainers/${{ matrix.language }}:latest
      context: .
      dockerfile: ${{ matrix.language }}/Dockerfile
      attest_id: ${{ matrix.language }}
      push: ${{ github.event_name != 'pull_request' }}

  attest:
    needs: publish

    strategy:
      matrix:
        language: ["python", "node"]

    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    uses: NathanVaughn/reusable-actions/.github/workflows/docker-attest.yml@main
    with:
      name: ghcr.io/nathanvaughn/devcontainers/${{ matrix.language }}
      attest_id: ${{ matrix.language }}
